const canvas=document.querySelector('#magic'),ctx=canvas.getContext('2d');
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduce.matches,w,h,t=0,last=0,nextBurst=.2,nextButterfly=.5,particles=[],rockets=[],stars=[],petals=[],dress=[],butterflies=[];
const colors=['255,238,194','237,210,255','255,209,233','210,236,255'];

const rand=(a,b)=>a+Math.random()*(b-a);
function progress(){return 0}
function point(x,y){const s=Math.max(w/1536,h/1024);return{x:(w-1536*s)/2+x*1536*s,y:(h-1024*s)/2+y*1024*s}}
function dressPoint(x,y){return point(x,y)}
function sparkle(x,y,r,a){ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#fff9ff';ctx.shadowColor='#e7cdff';ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(x,y-r);ctx.quadraticCurveTo(x+r*.12,y-r*.12,x+r*.65,y);ctx.quadraticCurveTo(x+r*.12,y+r*.12,x,y+r);ctx.quadraticCurveTo(x-r*.12,y+r*.12,x-r*.65,y);ctx.quadraticCurveTo(x-r*.12,y-r*.12,x,y-r);ctx.fill();ctx.restore()}
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:60},()=>({x:Math.random()*w,y:Math.random()*h*.6,r:rand(1,3),p:rand(0,6)}));petals=Array.from({length:28},()=>({x:Math.random()*w,y:Math.random()*h,r:rand(2,5),p:rand(0,6)}));dress=Array.from({length:45},()=>{const y=rand(.73,.90),spread=(y-.69)*.31;return{x:.50+rand(-spread,spread)+(y-.73)*.17,y,r:rand(1.5,4.5),p:rand(0,6),speed:rand(1.4,3.2)}});draw(0)}
function burst(x,y){const color=colors[Math.floor(Math.random()*colors.length)];for(let i=0;i<110;i++){const a=Math.PI*2*i/110,speed=rand(35,145);particles.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:rand(1.8,3.2),color,p:rand(0,6)})}particles=particles.slice(-700)}
function launch(x=rand(.12,.88)*w,y=rand(.10,.38)*h){rockets.push({x,y:h*.66,target:y,v:rand(220,310)})}
function butterfly(){const p=dressPoint(rand(.48,.55),rand(.79,.88));butterflies.push({x:p.x,y:p.y,age:0,life:rand(5,7),side:rand(-1,1),p:rand(0,6),size:rand(4,7)})}

// Image-relative flowing water and meadow glints, aligned with the selected background.
const falls=[{x:.108,y:.363,w:.025,h:.145},{x:.199,y:.413,w:.023,h:.105},{x:.288,y:.584,w:.025,h:.082},{x:.745,y:.563,w:.035,h:.11},{x:.891,y:.411,w:.034,h:.136}];
const meadow=Array.from({length:110},()=>({x:rand(0,1),y:rand(.47,.99),p:rand(0,6),r:rand(.6,2.5)})).filter(s=>Math.abs(s.x-.50)>.105);
function scenery(){
const scale=Math.max(w/1536,h/1024);
for(const f of falls){for(let i=0;i<12;i++){const q=(t*(.22+i*.009)+i*.137)%1;const x=f.x+(i/11-.5)*f.w*.8;const y=f.y+q*f.h;const a=point(x,y),b=point(x+.0007*Math.sin(t+i),Math.min(f.y+f.h,y+.012));const alpha=Math.sin(q*Math.PI)*(.12+.15*(.5+.5*Math.sin(t*2+i)));const g=ctx.createLinearGradient(a.x,a.y,b.x,b.y);g.addColorStop(0,'rgba(238,231,255,0)');g.addColorStop(.7,`rgba(240,245,255,${alpha})`);g.addColorStop(1,'rgba(255,255,255,0)');ctx.strokeStyle=g;ctx.lineWidth=scale*(.7+i%3*.45);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(i%4===0)sparkle(a.x,b.y,1.3,alpha*1.5)}}
for(const s of meadow){const p=point(s.x+Math.sin(t*.5+s.p)*.0008,s.y);const a=Math.pow(.5+.5*Math.sin(t*1.2+s.x*12+s.p),5);sparkle(p.x,p.y,s.r*(.8+a),a*.75)}
}
function draw(dt){ctx.clearRect(0,0,w,h);scenery();stars.forEach(s=>sparkle(s.x,s.y,s.r,.15+.65*Math.pow(.5+.5*Math.sin(t*1.5+s.p),3)));
rockets=rockets.filter(r=>{r.y-=r.v*dt;ctx.strokeStyle='#fff0d5';ctx.shadowColor='#ffe4ed';ctx.shadowBlur=12;ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(r.x,r.y+32);ctx.lineTo(r.x,r.y);ctx.stroke();if(r.y<=r.target){burst(r.x,r.y);return false}return true});ctx.shadowBlur=0;
particles=particles.filter(p=>p.life>0);particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=22*dt;p.vx*=Math.pow(.65,dt);p.vy*=Math.pow(.92,dt);const alpha=Math.min(1,p.life)*(.65+.35*Math.sin(t*16+p.p)**2);ctx.strokeStyle=`rgba(${p.color},${alpha})`;ctx.shadowColor=`rgb(${p.color})`;ctx.shadowBlur=7;ctx.lineWidth=1.25;ctx.beginPath();ctx.moveTo(p.x-p.vx*.09,p.y-p.vy*.09);ctx.lineTo(p.x,p.y);ctx.stroke()});ctx.shadowBlur=0;
petals.forEach(p=>{p.y+=dt*(12+p.r*2);p.x+=Math.sin(t*.7+p.p)*dt*15;if(p.y>h+10){p.y=-10;p.x=Math.random()*w}ctx.save();ctx.translate(p.x,p.y);ctx.rotate(t*.45+p.p);ctx.scale(.45+.5*Math.abs(Math.sin(t+p.p)),1);const g=ctx.createRadialGradient(0,0,0,0,0,p.r*2);g.addColorStop(0,'#fff');g.addColorStop(.5,'#ffe6fb');g.addColorStop(1,'#f3b4ed88');ctx.fillStyle=g;ctx.shadowColor='#ffe3fc';ctx.shadowBlur=12;ctx.beginPath();ctx.ellipse(0,0,p.r,p.r*1.8,0,0,7);ctx.fill();ctx.restore();if(Math.sin(t*2+p.p)>.8)sparkle(p.x,p.y,p.r*1.4,.8)});
dress.forEach(s=>{const p=dressPoint(s.x,s.y),a=Math.pow(.5+.5*Math.sin(t*s.speed+s.p),6);sparkle(p.x,p.y,s.r*(.5+a),a*.95)});
butterflies=butterflies.filter(b=>b.age<b.life);butterflies.forEach(b=>{b.age+=dt;b.y-=dt*rand(16,20);b.x+=dt*(b.side*13+Math.sin(b.age*2+b.p)*11);const alpha=Math.min(1,b.age*2,(b.life-b.age)*.8);ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.sin(b.age*2+b.p)*.25);ctx.scale(.25+.75*Math.abs(Math.sin(b.age*9+b.p)),1);ctx.globalAlpha=alpha;ctx.shadowColor='#e6dcff';ctx.shadowBlur=12;const size=b.size*(.65+Math.min(b.age,2)*.2);for(const side of [-1,1]){ctx.save();ctx.scale(side,1);const g=ctx.createLinearGradient(0,0,size,-size);g.addColorStop(0,'#ffffffff');g.addColorStop(1,'#dcceff55');ctx.fillStyle=g;ctx.strokeStyle='#fff5ff';ctx.lineWidth=.65;ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(size*.6,-size*1.6,size*1.7,-size*1.3,size,.1);ctx.bezierCurveTo(size*1.3,size,size*.4,size*1.2,0,0);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(size,-size*.8);ctx.stroke();ctx.restore()}ctx.restore();sparkle(b.x,b.y+7,1.5,alpha*.6)});
}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;if(!paused&&!document.hidden){t+=dt;if(t>nextBurst){launch();nextBurst=t+rand(.9,1.7)}if(t>nextButterfly){if(butterflies.length<5)butterfly();nextButterfly=t+rand(1.5,2.3)}draw(dt)}requestAnimationFrame(frame)}
function label(){document.body.classList.toggle('paused',paused);const b=document.querySelector('#pause');if(!b)return;b.textContent=paused?'Play ✧':'Pause ✧';b.setAttribute('aria-label',paused?'Play animation':'Pause animation')}
const pauseButton=document.querySelector('#pause');if(pauseButton)pauseButton.onclick=()=>{paused=!paused;label()};addEventListener('pointerdown',e=>{if(!paused&&!e.target.closest('button,a')&&e.clientY<h*.6)launch(e.clientX,e.clientY)});addEventListener('resize',resize);reduce.addEventListener('change',()=>{paused=reduce.matches;label();draw(0)});resize();label();requestAnimationFrame(frame);
